# Generated by Django 5.2.12 on 2026-03-14 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Required. Between 3 and 23 characters.', max_length=23, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(23)])),
            ],
        ),
    ]
