# Generated by Django 5.2.12 on 2026-03-16 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(help_text='Review must be between 25 and 20000 characters.', validators=[django.core.validators.MinLengthValidator(25), django.core.validators.MaxLengthValidator(20000)]),
        ),
    ]
