# Generated by Django 5.2.12 on 2026-03-15 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='No description yet', help_text='description must be between 10 and 250 characters.', validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(250)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='Please Update genre', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='release_year',
            field=models.IntegerField(default=1950, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2026)]),
            preserve_default=False,
        ),
    ]
