# Generated by Django 5.2.12 on 2026-03-16 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('title', 'platform')},
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(help_text='description must be between 5 and 800 characters.', validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(800)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.RemoveField(
            model_name='game',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='summary',
        ),
    ]
