# Generated by Django 5.2.12 on 2026-03-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_unique_together_alter_game_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
